### ISSUE TITLE
still pending tasks on commits by using PR Templates

### ISSUE THREAD

**Issue by dkroenke** [stilliard/github-task-list-completed#18]
Hi,
I'm using your App for checking the status of checkmarks by using PR-Templates: https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository. The App is configured as required status in the branch protection rules.When the PR opens, the app checks correctly and update immediately when i'm adding checkmarks to the open points.

The problem:
The checkboxes of the PR template are filled up then in the review process and completed shortly before the merge.
It happens that in the meantime more commits are added when the checklist is still not complete. This is then marked with the yellow dot in the commit. After merging (with the complete checklist) the merge commit has a green mark as status but the intermediate commits are still pending and task-list-complete wait for completing the checkmarks. 
I have no possibility to cancel this and the task is still running after some days.

Do you have an idea what i can do here?

**Comment by stilliard** [comment]
Hi @dkroenke 
Thanks for reaching out.

Atm we use the "in_progress" status with github to say when the checklist isn't complete, the check only runs on the latest commit so we only update the latest to "completed", any others made during changes etc. are left in the "in_progress" state because of this but the PR should pass fine as it's only checking the last commit's status. 

I'm not sure if there's a way we could change it to go back over old commits and re-run checks, but for now you should be safe to ignore the in progress time as atm it's more an indicator that when that check was done there were checklist items still needed. 

Hope this helps.
