### ISSUE TITLE
Check not listed

### ISSUE THREAD

**Issue by jamesphillpotts-fr** [stilliard/github-task-list-completed#3]
I've installed your app in a private repo, I'm editing the rule for the master branch, but when I enable `Require status checks to pass before merging`, I can't see your check listed. Any ideas?

**Comment by stilliard** [comment]
Hi @jamesphillpotts-fr , Not sure if this is still affecting you but I had this when I first enabled the check when i already had pull requests open, the check will only run once the pull request is created or updated since installing the app, for existing pull requests try a minor update of the body etc.
Thanks.

**Comment by jamesphillpotts-fr** [comment]
Hi @stilliard, yep seems sorted now :man_shrugging:
