### ISSUE TITLE
Status check runs indefinitely

### ISSUE THREAD

**Issue by s-gbz** [stilliard/github-task-list-completed#30]
Hey there,
thanks for creating this useful plugin.

I noticed that the check is running without a timeout and I'm a little worried if this will consume my available [CI/CD minutes](https://github.com/pricing).

![image](https://user-images.githubusercontent.com/23424538/186361848-0792f680-99fe-4266-9694-b1d5a6837e32.png)

Is there a possibility for the check to simply fail if the tasks are not ticked off?
The check might be rerun everytime the PR description is updated (though I'm afraid this is impossible).

Anyway, can you help me out with the first question?

**Comment by stilliard** [comment]
Hey @s-gbz,

No worries, this app is free and doesn't use any of your CI/CD minutes. 

Though visually in github it shows as constantly running, the check only runs for less than a second. 
The flow is, Github sends us the first ping to check the pull request, we then respond to either say it's still in progress if there's checklists remaining, or success if the check is complete. We then instantly close this off, even though github shows it as still running, that's just because we tell them it's still in progress. 

Hope this helps
